# Cloud Build configuration for diaremot2-on Cloud Run deployment
# Builds HTTP service with FastAPI

timeout: 1800s

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: 'ALLOW_LOOSE'

substitutions:
  _IMAGE_NAME: 'diaremot2-on'
  _IMAGE_TAG: 'latest'
  _GCR_HOSTNAME: 'gcr.io'
  _PYTHON_VERSION: '3.11'

steps:
  # Step 1: Build Cloud Run optimized image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-cloudrun-image'
    args:
      - 'build'
      - '-t'
      - '${_GCR_HOSTNAME}/${PROJECT_ID}/${_IMAGE_NAME}:${_IMAGE_TAG}'
      - '-t'
      - '${_GCR_HOSTNAME}/${PROJECT_ID}/${_IMAGE_NAME}:${BUILD_ID}'
      - '-f'
      - 'Dockerfile.cloudrun'
      - '--build-arg'
      - 'PYTHON_VERSION=${_PYTHON_VERSION}'
      - '.'
    waitFor: ['-']

  # Step 2: Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-latest'
    args:
      - 'push'
      - '${_GCR_HOSTNAME}/${PROJECT_ID}/${_IMAGE_NAME}:${_IMAGE_TAG}'
    waitFor: ['build-cloudrun-image']

  # Step 3: Push build ID tag
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-build-id'
    args:
      - 'push'
      - '${_GCR_HOSTNAME}/${PROJECT_ID}/${_IMAGE_NAME}:${BUILD_ID}'
    waitFor: ['build-cloudrun-image']

images:
  - '${_GCR_HOSTNAME}/${PROJECT_ID}/${_IMAGE_NAME}:${_IMAGE_TAG}'
  - '${_GCR_HOSTNAME}/${PROJECT_ID}/${_IMAGE_NAME}:${BUILD_ID}'
